name: monsalon_pro
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  firebase_storage: ^11.1.1
  cloud_firestore: ^4.5.2
  google_sign_in: ^6.1.0
  provider: ^6.0.5

  flutter_svg: ^2.0.5
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.1.10
  http: ^0.13.5
  lottie: ^2.3.2

  checkbox_grouped: ^1.8.2
  animated_custom_dropdown: ^1.5.0
  image_picker: ^0.8.7+4
  photo_view: ^0.14.0
  flutter_image_compress: ^1.1.3
  badges: ^3.1.1
  firebase_messaging: ^14.4.1
  getwidget: ^3.1.1
  flutter_localization: ^0.1.10
  jiffy: ^5.0.0
  shared_preferences: ^2.1.0
  pretty_qr_code: ^2.0.3
  qr_code_scanner: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/animation/
    - assets/images/


  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Black.ttf
        - asset: fonts/Rubik-Bold.ttf
        - asset: fonts/Rubik-ExtraBold.ttf
        - asset: fonts/Rubik-Light.ttf
        - asset: fonts/Rubik-Medium.ttf
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-SemiBold.ttf
        - asset: fonts/Rubik-VariableFont_wght.ttf