// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBJLAwx75grxl2sxgi5s4PbJx1UJRnv00',
    appId: '1:1096223098682:web:13d2424d647fa74561f203',
    messagingSenderId: '1096223098682',
    projectId: 'monsalon-dz',
    authDomain: 'monsalon-dz.firebaseapp.com',
    storageBucket: 'monsalon-dz.appspot.com',
    measurementId: 'G-BNEWMXCJM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCESr0hQ1ZmV5eqEMdcHWDgDMLQVsehlI8',
    appId: '1:1096223098682:android:4d0c8e6764ba75ee61f203',
    messagingSenderId: '1096223098682',
    projectId: 'monsalon-dz',
    storageBucket: 'monsalon-dz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjSqSW4vUBK3mDfOxbP33ypbnlucRaMhU',
    appId: '1:1096223098682:ios:0bdab8c30039451361f203',
    messagingSenderId: '1096223098682',
    projectId: 'monsalon-dz',
    storageBucket: 'monsalon-dz.appspot.com',
    androidClientId: '1096223098682-herhl3ma8r7fpo20soe25a7ks4u1m0l3.apps.googleusercontent.com',
    iosClientId: '1096223098682-9babqjnrhnqmfpehcml41svvf59f9i5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.monsalonPro',
  );
}
